### PR TITLE
Spigot and craftbukkit installers

### PR DESCRIPTION
**Pull request by MarMed**
Not entirely sure my formatting is correct.

### CODE REVIEW

**Comment by Raekye** [comment]
Checked your PR over at the recipes repo too. The version isn't used/isn't flexible, but doesn't seem like there's anything we can do about it (or does spigot provide versioned links for BuildTools?)

You could use `pushd` and `popd` (or `cd ..`) instead of `cd "$MINECRAFT_DIR"`, but it's not an issue. Also technically missing the commas for the array :P but I can fix that when I commit other misc. changes I have in my workspace

Happy to merge, but I'll just double check tomorrow, in case I think of anything later, which happens many times when I do things at 5am xD Thanks!

**Comment by MarMed** [comment]
I figured you could write it better but I had free time and noticed you added install scripts. I wasn't actually aware of pushd and popd. I apparently have a lot to learn because what's the commas for the array thing?

**Comment by MarMed** [comment]
Oh and you could specify which build of BuildTools in the version but I don't really know if it'd matter.

**Comment by Raekye** [comment]
Sorry I was really undescriptive xD In `config/application.rb` you add entries the array of flavours, but missing the extra commas between the new elements. But I can fix it along with other misc changes I have. Thanks!

**Pull request merged**
