### PR TITLE
New layout for server control panel

### PR DESCRIPTION
**Pull request by binary-koan**
Screenshot of the new layout (for posterity):

This change also

* Makes the navbar background white instead of black (I think it looks cleaner but it's easy enough to revert if you don't agree)
* Makes "Create server" a separate page - the servers list now has a big green "create" button instead of a form to the right (debatable whether this is an improvement)

It used to contain a login screen overhaul as well, but it wasn't properly finished so I'll do it properly at some point.

### CODE REVIEW

**Comment by Raekye** [comment]
Wow this looks amazing! I'll try to go over it carefully tomorrow (probably won't have much)

**Comment by Raekye** [comment]
Looks good! Thanks for your contribution! I'm just fixing up the tests

**Comment by binary-koan** [comment]
Great, thanks! Should've tried running the tests - my bad ...

**Comment by Raekye** [comment]
No worries, although testing is great and I think Gamocosm has pretty comprehensive testing (for a relatively non-convention application that's hard/annoying to test), it's quite a pain to do because of it xD Unless I missed something your code seems pretty good and I really appreciate it! Look forward to the rest of it xD (you don't have to worry about the tests if you don't want haha)

**Pull request merged**
